version: '3.1'
services:
  db:
    image: postgres
    restart: always
    network_mode: "host"
    environment:
      POSTGRES_PASSWORD: mypassword

    volumes:
      - ./postgres-data:/var/lib/postgresql/data