version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: locadora_db
    ports:
      - "5432:5432"

  locadora-api:
    image: ilussencio/locadora-api
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: locadora_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    depends_on:
      - db
